<!--
  One legal document — Privacy Policy or Terms of Service — rendered for
  one locale, with the provenance that makes a translated legal page
  honest about what it is.

  Shared by /privacy and /terms because the two pages differ only in
  which document they name: a second copy would be a second place for a
  provenance rule to be got wrong.

  The body HTML comes from $lib/legal/documents.ts, generated by
  tools/legal/render.mjs from legal/*.md. Everything around it — heading,
  version line, translation notice — comes from the message catalogue, so
  no user-visible string is hard-coded in the generator.

  The staleness contract, enforced in the generator: `effectiveDate` is
  null exactly when a translation has fallen behind the source it was
  translated from. This component therefore *cannot* present old wording
  under the current effective date — there is no date to present. It says
  which version the wording means, what is actually in force, and links
  to the authoritative British English text.
-->

<script lang="ts">
  import { reveal } from "$lib/motion";
  import {
    DEFAULT_LOCALE,
    SOURCE_LEGAL_LINKS,
    fmt,
    messagesFor,
    rich,
    splitAt,
    type Locale,
  } from "$lib/i18n";
  import {
    LEGAL_CURRENT,
    LEGAL_DOCUMENTS,
    type LegalDocKey,
    type LegalRendering,
  } from "$lib/legal/documents";

  let { doc, locale }: { doc: LegalDocKey; locale: Locale } = $props();

  const m = $derived(messagesFor(locale).legal);

  // A locale can exist on the site before its legal translation does. In
  // that case the authoritative source-locale text is served rather than
  // an empty page, and `lang` on the article below tells assistive
  // technology which language it is actually reading.
  const rendering = $derived(
    (LEGAL_DOCUMENTS[doc] as Record<string, LegalRendering | undefined>)[
      locale
    ] ?? LEGAL_DOCUMENTS[doc][DEFAULT_LOCALE],
  );

  const heading = $derived(
    doc === "privacy" ? m.privacyHeading : m.termsHeading,
  );

  /** A date the way the active locale writes it. */
  function formatDate(iso: string, inLocale: Locale): string {
    return new Intl.DateTimeFormat(inLocale, {
      day: "numeric",
      month: "long",
      year: "numeric",
      timeZone: "UTC",
    }).format(new Date(`${iso}T00:00:00Z`));
  }

  // Split rather than interpolated: `{date}` stands in for a <time>
  // element, and the catalogue carries no HTML. Translators keep control
  // of the word order on both sides of it.
  const versionParts = $derived(
    splitAt(fmt(m.versionLine, { version: rendering.version }), "date"),
  );

  const translation = $derived(rendering.translation);

  const notice = $derived(
    translation === null
      ? null
      : rich(
          translation.stale
            ? fmt(m.staleNotice, {
                version: translation.sourceVersion,
                currentVersion: LEGAL_CURRENT.version,
                currentDate: formatDate(
                  LEGAL_CURRENT.effectiveDateISO,
                  locale,
                ),
              })
            : fmt(m.translationNotice, {
                version: translation.sourceVersion,
                reviewedOn: formatDate(translation.reviewedOn, locale),
              }),
          locale,
          // `sourceDoc` resolves to this document's own British English
          // page, which is why it is a call-site link rather than a
          // catalogue-wide one.
          { sourceDoc: SOURCE_LEGAL_LINKS[doc] },
        ),
  );
</script>

<article
  class="site-container prose py-16 reveal"
  lang={rendering.locale}
  use:reveal
>
  <h1>{heading}</h1>

  <p>
    <strong>
      {#if rendering.effectiveDate !== null && rendering.effectiveDateISO !== null}
        {versionParts[0]}<time datetime={rendering.effectiveDateISO}
          >{rendering.effectiveDate}</time
        >{versionParts[1]}
      {:else}
        {fmt(m.versionLineUndated, { version: rendering.version })}
      {/if}
    </strong>
  </p>

  {#if notice !== null}
    <aside
      class="legal-provenance"
      class:stale={translation?.stale}
      aria-label={m.provenanceLabel}
    >
      <p>{@html notice}</p>
    </aside>
  {/if}

  {@html rendering.html}
</article>

<style>
  /* Set apart from the legal prose it annotates: this is the site
     talking about the document, not part of the document. */
  .legal-provenance {
    margin: var(--space-lg) 0;
    padding: var(--space-md) var(--space-lg);
    border-inline-start: 3px solid var(--color-primary-600);
    border-radius: var(--radius-md);
    background: var(--surface-sunken);
  }

  /* A stale translation is a warning, not a footnote. */
  .legal-provenance.stale {
    border-inline-start-color: var(--color-text-950);
  }

  .legal-provenance p {
    margin: 0;
  }
</style>
